### ISSUE TITLE
compatible with solidJs 1.5.0

### ISSUE THREAD

**Issue by hhhxxjj** [DigiChanges/solid-experience#66]
createResource(authRepository.getAllPermissions()) isn't compatible with solidJs 1.5.0.

the error is as follows:

`
TS2345: Argument of type '(urlSearchParams?: QueryParams) => Promise<PermissionListResponse>' is not assignable to parameter of type 'ResourceFetcher<true, PermissionListResponse, unknown>'.   Types of parameters 'urlSearchParams' and 'k' are incompatible.     Type 'true' has no properties in common with type 'QueryParams'
`

**Comment by Murzbul** [comment]
Thanks for sharing the bug.

We will be updating it soon.

**Comment by hhhxxjj** [comment]
Thanks for the quick response. @Murzbul
