### ISSUE TITLE
The command `yarn lint` is not working

### ISSUE THREAD

**Issue by veronicadip** [DigiChanges/solid-experience#92]
I've tried to use the commands `yarn lint` and `yarn lint-fix` to format the code but is not working. In both cases, the console throws me this error:

```
Oops! Something went wrong! :(

ESLint: 8.45.0

No files matching the pattern "./src" were found.
Please check for typing mistakes in the pattern.
```

The thing is that I'm in the `solid-experience` folder, so it should find the "./src" directory. Just in case, I ran the `ls` command to see all the files in my current directory, but as expected, the `src` folder was there.

I've also tried running that script with npm and pnpm.

**Comment by Murzbul** [comment]
Thank you for the issue!
